import * as React from 'react'

import { Container } from 'components/parts/Container'
import { Content } from 'components/parts/Content'
import { Header, Nav, NavItem } from 'components/parts/Header'
import { Footer } from 'components/parts/Footer'
import styled from 'styled-components'
interface Props {
  children: React.ReactNode
}

const FirstNavItem = styled(NavItem)`
  margin-right: auto;
`

export const Base: React.SFC<Props> = ({ children }: Props) => (
  <>
    <Header>
      <Nav>
        <FirstNavItem href="/">
          <h1> Nothing ventured、nothing gain</h1>
        </FirstNavItem>
        <NavItem href="/">HOME</NavItem>
        <NavItem href="/about">ABOUT</NavItem>
      </Nav>
    </Header>
    <Container>
      <Content>{children}</Content>
      <Footer>
        <p>
          generated by{' '}
          <a
            href="https://react-static.js.org"
            target="_blank"
            rel="noopener noreferrer"
          >
            React Static
          </a>
        </p>
        <p>
          hosted by{' '}
          <a
            href="https://www.netlify.com/"
            target="_blank"
            rel="noopener noreferrer"
          >
            netlify
          </a>
        </p>
      </Footer>
    </Container>
  </>
)
