import * as React from 'react'

import { Container } from 'components/parts/Container'
import { Content } from 'components/parts/Content'
import { Header, Nav, NavItem } from 'components/parts/Header'
import { Footer } from 'components/parts/Footer'

interface Props {
  children: React.ReactNode
}

export const Base: React.SFC<Props> = ({ children }: Props) => (
  <Container>
    <Header>
      <Nav>
        <NavItem href="/">HOME</NavItem>
        <NavItem href="/about">ABOUT</NavItem>
      </Nav>
    </Header>
    <Content>{children}</Content>
    <Footer>
      <p>
        generated by{' '}
        <a
          href="https://react-static.js.org"
          target="_blank"
          rel="noopener noreferrer"
        >
          React Static
        </a>
      </p>
      <p>
        hosted by{' '}
        <a
          href="https://www.netlify.com/"
          target="_blank"
          rel="noopener noreferrer"
        >
          netlify
        </a>
      </p>
    </Footer>
  </Container>
)
