import * as React from 'react'

import Container from '@material-ui/core/Container'
import Grid from '@material-ui/core/Grid'
import { Header } from 'components/parts/Header'
import Typography from '@material-ui/core/Typography'
import Divider from '@material-ui/core/Divider'
interface Props {
  children: React.ReactNode
}

export const Base: React.SFC<Props> = ({ children }: Props) => (
  <>
    <Container maxWidth="lg">
      <Header />
      <Grid
        container
        direction="column"
        justify="space-between"
        alignItems="center"
      >
        {/* Main content */}
        <Grid item xs={12} md={6}>
          {children}
        </Grid>
      </Grid>
    </Container>
    <Divider variant="middle" />
    <footer>
      <Container maxWidth="lg">
        <Typography
          variant="subtitle1"
          align="center"
          color="textSecondary"
          component="p"
        >
          generated by{' '}
          <a
            href="https://react-static.js.org"
            target="_blank"
            rel="noopener noreferrer"
          >
            React Static
          </a>
        </Typography>
        <Typography
          variant="subtitle1"
          align="center"
          color="textSecondary"
          component="p"
        >
          hosted by{' '}
          <a
            href="https://www.netlify.com/"
            target="_blank"
            rel="noopener noreferrer"
          >
            netlify
          </a>
        </Typography>
      </Container>
    </footer>
  </>
)
